"""GraphMind AI — Pydantic Schemas

Central schema definitions for all API request/response models.
Used by FastAPI for automatic OpenAPI documentation & validation.
"""

from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, Field


# ── Chat ─────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    """Natural-language question sent to the LLM query engine."""
    message: str = Field(..., min_length=1, max_length=2000, description="User question in plain English")
    history: list[dict] | None = Field(None, description="Previous conversation turns for context")


class ChatResponse(BaseModel):
    """Structured response from the query engine."""
    answer: str = Field(..., description="Narrative answer generated by the LLM")
    sql: str | None = Field(None, description="SQL query generated (if applicable)")
    data: list[dict] | None = Field(None, description="Query result rows")
    referencedNodes: list[str] = Field(default_factory=list, description="Graph node IDs mentioned in results")


class ExportRequest(BaseModel):
    """Request to export query result data."""
    data: list[dict] = Field(..., description="Rows to export")
    format: Literal["csv", "json"] = Field("csv", description="Output file format")


class Suggestion(BaseModel):
    """Pre-built example query."""
    text: str
    category: str


# ── Graph ────────────────────────────────────────────────────────

class GraphNode(BaseModel):
    id: str
    type: str
    label: str
    color: str
    val: int | float = 1


class GraphLink(BaseModel):
    source: str
    target: str
    type: str


class GraphDataResponse(BaseModel):
    """Full graph payload for the force-directed visualisation."""
    nodes: list[GraphNode]
    links: list[GraphLink]


class NeighborNode(BaseModel):
    id: str
    type: str
    label: str
    edgeType: str
    direction: Literal["incoming", "outgoing"]


class NodeDetailResponse(BaseModel):
    """Detailed node information with all properties and neighbors."""
    id: str
    properties: dict[str, Any] = Field(default_factory=dict)
    neighbors: list[NeighborNode] = Field(default_factory=list)


class SearchResult(BaseModel):
    id: str
    type: str
    label: str
    color: str


class StatsResponse(BaseModel):
    """Graph statistics and node/edge counts by type."""
    totalNodes: int
    totalEdges: int
    nodesByType: dict[str, int]
    edgesByType: dict[str, int]


# ── Analytics ────────────────────────────────────────────────────

class FunnelData(BaseModel):
    orders: int
    delivered: int
    billed: int
    paid: int


class TopCustomer(BaseModel):
    name: str
    orders: int
    revenue: float


class TopProduct(BaseModel):
    name: str
    orders: int


class StatusCount(BaseModel):
    status: str | None
    count: int


class MonthlyTrend(BaseModel):
    month: str
    revenue: float
    invoices: int


class AnalyticsResponse(BaseModel):
    """KPI dashboard analytics for the O2C dataset."""
    funnel: FunnelData
    totalRevenue: float
    topCustomers: list[TopCustomer]
    topProducts: list[TopProduct]
    statusDistribution: list[StatusCount]
    monthlyTrend: list[MonthlyTrend]


# ── Path Finder ──────────────────────────────────────────────────

class PathResponse(BaseModel):
    """Shortest path between two graph nodes."""
    path: list[SearchResult]
    edges: list[GraphLink]
    length: int


# ── Health / System ──────────────────────────────────────────────

class HealthResponse(BaseModel):
    """API health check with system status."""
    status: str = "ok"
    version: str
    graph: StatsResponse
    database: dict[str, Any] = Field(default_factory=dict)
    uptime_seconds: float


class ErrorResponse(BaseModel):
    """Standard error envelope for all non-2xx responses."""
    error: str
    detail: str | None = None
